# Generated by Django 4.0.6 on 2022-08-03 06:05

import django.core.validators
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('ecom', '0006_auto_20220730_2233'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customer',
            name='mobile',
            field=models.CharField(blank=True, max_length=10, validators=[django.core.validators.RegexValidator(regex='^\\+?1?\\d{10}$')]),
        ),
        migrations.AlterField(
            model_name='orders',
            name='mobile',
            field=models.CharField(max_length=10, null=True),
        ),
    ]
